### ISSUE TITLE
Error in importing `vertexai.preview.generative_models` in `generative-ai/gemini/use-cases/intro_multimodal_use_cases.ipynb`

### ISSUE THREAD

**Issue by said-rasidin** [GoogleCloudPlatform/generative-ai#363] opened 2024-01-29 15:51 UTC
https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/intro_multimodal_use_cases.ipynb

Error in importing this module

```py
from vertexai.preview.generative_models import (
    GenerationConfig,
    GenerativeModel,
    Image,
    Part,
)
```

the error code is

```
2024-01-29 15:46:26.194779: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 from vertexai.preview.generative_models import (
      2     GenerationConfig,
      3     GenerativeModel,
      4     Image,
      5     Part,
      6 )

File ~/.local/lib/python3.10/site-packages/vertexai/__init__.py:18
     15 """The vertexai module."""
     17 from google.cloud.aiplatform import init
---> 18 from vertexai import preview
     20 __all__ = [
     21     "init",
     22     "preview",
     23 ]

File ~/.local/lib/python3.10/site-packages/vertexai/preview/__init__.py:20
      1 # -*- coding: utf-8 -*-
      2 
      3 # Copyright 2023 Google LLC
   (...)
     15 # limitations under the License.
     16 #
     18 from google.cloud.aiplatform.metadata import metadata
---> 20 from vertexai.preview import developer
     21 from vertexai.preview import hyperparameter_tuning
     22 from vertexai.preview import initializer

File ~/.local/lib/python3.10/site-packages/vertexai/preview/developer/__init__.py:18
      1 # -*- coding: utf-8 -*-
      2 
      3 # Copyright 2023 Google LLC
   (...)
     15 # limitations under the License.
     16 #
---> 18 from vertexai.preview._workflow.serialization_engine import (
     19     any_serializer,
     20 )
     21 from vertexai.preview._workflow.serialization_engine import (
     22     serializers_base,
     23 )
     24 from vertexai.preview._workflow.shared import configs

File ~/.local/lib/python3.10/site-packages/vertexai/preview/_workflow/serialization_engine/any_serializer.py:30
     28 from google.cloud.aiplatform import base
     29 from google.cloud.aiplatform.utils import gcs_utils
---> 30 from vertexai.preview._workflow.serialization_engine import (
     31     serializers,
     32     serializers_base,
     33 )
     34 from vertexai.preview._workflow.shared import (
     35     supported_frameworks,
     36 )
     38 from packaging import requirements

File ~/.local/lib/python3.10/site-packages/vertexai/preview/_workflow/serialization_engine/serializers.py:52
     49 SERIALIZATION_METADATA_FRAMEWORK_KEY = "framework"
     51 try:
---> 52     from tensorflow import keras
     53     import tensorflow as tf
     55     KerasModel = keras.models.Model

File /opt/conda/lib/python3.10/site-packages/tensorflow/__init__.py:37
     34 import sys as _sys
     35 import typing as _typing
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     40 # Make sure code inside the TensorFlow codebase can use tf2.enabled() at import.

File /opt/conda/lib/python3.10/site-packages/tensorflow/python/__init__.py:37
     29 # We aim to keep this file minimal and ideally remove completely.
     30 # If you are adding a new file with @tf_export decorators,
     31 # import it in modules_with_exports.py instead.
     32 
     33 # go/tf-wildcard-import
     34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
---> 37 from tensorflow.python.eager import context
     39 # pylint: enable=wildcard-import
     40 
     41 # Bring in subpackages.
     42 from tensorflow.python import data

File /opt/conda/lib/python3.10/site-packages/tensorflow/python/eager/context.py:28
     25 from absl import logging
     26 import numpy as np
---> 28 from tensorflow.core.framework import function_pb2
     29 from tensorflow.core.protobuf import config_pb2
     30 from tensorflow.core.protobuf import coordination_config_pb2

File /opt/conda/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py:16
     11 # @@protoc_insertion_point(imports)
     13 _sym_db = _symbol_database.Default()
---> 16 from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
     17 from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
     18 from tensorflow.core.framework import op_def_pb2 as tensorflow_dot_core_dot_framework_dot_op__def__pb2

File /opt/conda/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py:16
     11 # @@protoc_insertion_point(imports)
     13 _sym_db = _symbol_database.Default()
---> 16 from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
     17 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     18 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2

File /opt/conda/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py:16
     11 # @@protoc_insertion_point(imports)
     13 _sym_db = _symbol_database.Default()
---> 16 from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
     17 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     18 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2

File /opt/conda/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py:16
     11 # @@protoc_insertion_point(imports)
     13 _sym_db = _symbol_database.Default()
---> 16 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     17 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2
     20 DESCRIPTOR = _descriptor.FileDescriptor(
     21   name='tensorflow/core/framework/resource_handle.proto',
     22   package='tensorflow',
   (...)
     26   ,
     27   dependencies=[tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_types__pb2.DESCRIPTOR,])

File /opt/conda/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py:36
     13 _sym_db = _symbol_database.Default()
     18 DESCRIPTOR = _descriptor.FileDescriptor(
     19   name='tensorflow/core/framework/tensor_shape.proto',
     20   package='tensorflow',
   (...)
     23   serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
     24 )
     29 _TENSORSHAPEPROTO_DIM = _descriptor.Descriptor(
     30   name='Dim',
     31   full_name='tensorflow.TensorShapeProto.Dim',
     32   filename=None,
     33   file=DESCRIPTOR,
     34   containing_type=None,
     35   fields=[
---> 36     _descriptor.FieldDescriptor(
     37       name='size', full_name='tensorflow.TensorShapeProto.Dim.size', index=0,
     38       number=1, type=3, cpp_type=2, label=1,
     39       has_default_value=False, default_value=0,
     40       message_type=None, enum_type=None, containing_type=None,
     41       is_extension=False, extension_scope=None,
     42       serialized_options=None, file=DESCRIPTOR),
     43     _descriptor.FieldDescriptor(
     44       name='name', full_name='tensorflow.TensorShapeProto.Dim.name', index=1,
     45       number=2, type=9, cpp_type=9, label=1,
     46       has_default_value=False, default_value=_b("").decode('utf-8'),
     47       message_type=None, enum_type=None, containing_type=None,
     48       is_extension=False, extension_scope=None,
     49       serialized_options=None, file=DESCRIPTOR),
     50   ],
     51   extensions=[
     52   ],
     53   nested_types=[],
     54   enum_types=[
     55   ],
     56   serialized_options=None,
     57   is_extendable=False,
     58   syntax='proto3',
     59   extension_ranges=[],
     60   oneofs=[
     61   ],
     62   serialized_start=149,
     63   serialized_end=182,
     64 )
     66 _TENSORSHAPEPROTO = _descriptor.Descriptor(
     67   name='TensorShapeProto',
     68   full_name='tensorflow.TensorShapeProto',
   (...)
    100   serialized_end=182,
    101 )
    103 _TENSORSHAPEPROTO_DIM.containing_type = _TENSORSHAPEPROTO

File ~/.local/lib/python3.10/site-packages/google/protobuf/descriptor.py:553, in FieldDescriptor.__new__(cls, name, full_name, index, number, type, cpp_type, label, default_value, message_type, enum_type, containing_type, is_extension, extension_scope, options, serialized_options, has_default_value, containing_oneof, json_name, file, create_key)
    547 def __new__(cls, name, full_name, index, number, type, cpp_type, label,
    548             default_value, message_type, enum_type, containing_type,
    549             is_extension, extension_scope, options=None,
    550             serialized_options=None,
    551             has_default_value=True, containing_oneof=None, json_name=None,
    552             file=None, create_key=None):  # pylint: disable=redefined-builtin
--> 553   _message.Message._CheckCalledFromGeneratedFile()
    554   if is_extension:
    555     return _message.default_pool.FindExtensionByName(full_name)

TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by Biparker** [comment] 2024-01-29 19:45
As of 2:45 PM EST on 1/26, this problem has not been corrected.  Wait time for online support from Qwiklabs is 15 - 30 minutes, and no answered provided, even after sharing error code.

**Comment by holtskinner** [comment] 2024-01-30 16:03
The change in https://github.com/GoogleCloudPlatform/generative-ai/pull/365 can also fix this issue. Seems to be either that the `protobuf` library isn't installing correctly or that there's a bug in the default installed version of the library. Asking @komaljoshi-SSK for clarity.

**Comment by rocpoc** [comment] 2024-01-30 16:55
Changes should be rolling out to Cloud Skills Boost deployments momentarily.

**Comment by polong-lin** [comment] 2024-01-31 12:06
This is been confirmed as fixed on the Skills Boost side -- thank you!

**Closed by polong-lin** 2024-01-31 12:06 UTC

**Comment by dhruv-anand-aintech** [comment] 2024-08-19 18:45
Please state which packages should be updated and to which version range. I'm still facing this error deep in an unrelated library's stack

**Comment by dhruv-anand-aintech** [comment] 2024-08-20 21:36
apparently `pip install vertexai` works for `google-cloud-aiplatform-1.42.0 protobuf-4.25.4 vertexai-1.63.0`
