### ISSUE TITLE
[Feat]: tokenized

### ISSUE THREAD

**Issue by gauravgandhi1315** [GoogleCloudPlatform/generative-ai#1067] opened 2024-09-10 18:55 UTC
### Describe the solution you'd like

REST api  json object has `text`: "this is a prompt" fields. Instead of text, would it be possible to send already tokenized data ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment] 2024-09-10 21:24
This is a duplicate of #984

**Closed by holtskinner** 2024-09-10 21:24 UTC
